--[[
	permission_users.lua

	Distributed as Public Domain, with no license.
	This file was generated by a script.
--]]

return {
  ["50fffff"] = {
    group = "guest",
    lastGroup = "guest"
  },
  AAA_THREAT = {
    group = "guest",
    lastGroup = "guest"
  },
  Aerost = {
    group = "regular",
    lastGroup = "regular"
  },
  Aiomi = {
    group = "regular",
    lastGroup = "regular"
  },
  Artemiye = {
    group = "guest",
    lastGroup = "guest"
  },
  Arti20 = {
    group = "guest",
    lastGroup = "guest"
  },
  BLYAAAAAT = {
    group = "guest",
    lastGroup = "guest"
  },
  Bandwurm = {
    group = "guest",
    lastGroup = "guest"
  },
  BenSierra = {
    group = "guest",
    lastGroup = "guest"
  },
  Breadface = {
    group = "guest",
    lastGroup = "guest"
  },
  CallMeTaste = {
    group = "regular",
    lastGroup = "regular"
  },
  Coldronald = {
    group = "regular",
    lastgroup = "regular"
  },
  Conor0709 = {
    group = "guest",
    lastGroup = "guest"
  },
  Copperbotte = {
    group = "regular",
    lastGroup = "regular"
  },
  CrazyCrabEater = {
    group = "guest",
    lastGroup = "guest"
  },
  DQ_Shell = {
    group = "guest",
    lastGroup = "guest"
  },
  Darkdna1738 = {
    group = "guest",
    lastGroup = "guest"
  },
  Delta124 = {
    group = "guest",
    lastGroup = "guest"
  },
  DeltaNedas = {
    group = "regular",
    lastGroup = "regular"
  },
  Dennis_Riley = {
    group = "guest",
    lastGroup = "guest"
  },
  ["Diablo-D3"] = {
    group = "regular",
    lastGroup = "regular"
  },
  Dra6o0n = {
    group = "guest",
    lastGroup = "guest"
  },
  Dunes = {
    group = "guest",
    lastGroup = "guest"
  },
  ElderAxe = {
    group = "admin",
    lastGroup = "admin"
  },
  Ethotron = {
    group = "guest",
    lastGroup = "guest"
  },
  Everdraed = {
    group = "guest",
    lastGroup = "guest"
  },
  FieldFrog = {
    group = "guest",
    lastGroup = "guest"
  },
  Fridjit = {
    group = "guest",
    lastGroup = "guest"
  },
  Furancebob = {
    group = "guest",
    lastGroup = "guest"
  },
  Geertje123 = {
    group = "guest",
    lastGroup = "guest"
  },
  Gizan = {
    group = "guest",
    lastGroup = "guest"
  },
  Hagaret = {
    group = "regular",
    lastGroup = "regular"
  },
  Harcourt = {
    group = "guest",
    lastGroup = "guest"
  },
  Harkonnen = {
    group = "admin",
    lastGroup = "admin"
  },
  Haybale = {
    group = "regular",
    lastGroup = "regular"
  },
  HighInFiberOptics = {
    group = "regular",
    lastGroup = "regular"
  },
  Hobnob = {
    group = "regular",
    lastGroup = "regular"
  },
  Hummerback = {
    group = "guest",
    lastGroup = "guest"
  },
  IrrelevantScrub = {
    group = "moderator",
    lastGroup = "moderator",
    lastgroup = "regular"
  },
  JJWildcat = {
    group = "guest",
    lastGroup = "guest"
  },
  JerAleman = {
    group = "guest",
    lastGroup = "guest"
  },
  Jono4728 = {
    group = "regular",
    lastGroup = "regular"
  },
  Kevin_Ar18 = {
    group = "regular",
    lastGroup = "regular"
  },
  Klausausderkasse = {
    group = "guest",
    lastGroup = "guest"
  },
  LockeCorp = {
    group = "guest",
    lastGroup = "guest"
  },
  Malison = {
    group = "regular",
    lastGroup = "regular"
  },
  Mawstero = {
    group = "regular",
    lastGroup = "regular"
  },
  MercBenz1212 = {
    group = "admin",
    lastGroup = "admin"
  },
  Merc_Plays = {
    group = "operator",
    lastGroup = "operator"
  },
  Minifinger = {
    group = "regular",
    lastGroup = "regular"
  },
  Molter = {
    group = "regular",
    lastGroup = "regular"
  },
  Morgan3rd = {
    group = "regular",
    lastGroup = "regular"
  },
  Mouldy = {
    group = "admin",
    lastGroup = "admin"
  },
  MrMorgansNiggerSlave = {
    group = "guest",
    lastGroup = "guest"
  },
  NARDO2013 = {
    group = "guest",
    lastGroup = "guest"
  },
  NWorlder = {
    group = "guest",
    lastGroup = "guest"
  },
  NerdNummy = {
    group = "guest",
    lastGroup = "guest"
  },
  Nouk = {
    group = "Jail",
    lastGroup = "Jail"
  },
  Numbian = {
    group = "guest",
    lastGroup = "guest"
  },
  Patton1918 = {
    group = "guest",
    lastGroup = "guest"
  },
  PhantomBrk = {
    group = "Jail",
    lastGroup = "Jail"
  },
  Pirion = {
    group = "regular",
    lastGroup = "regular"
  },
  PogomanD = {
    group = "regular",
    lastGroup = "regular"
  },
  Renkairu = {
    group = "guest",
    lastGroup = "guest"
  },
  RevDr = {
    group = "regular",
    lastGroup = "regular"
  },
  Santilla = {
    group = "guest",
    lastGroup = "guest"
  },
  Seico = {
    group = "regular",
    lastGroup = "regular"
  },
  SnailsAttack = {
    group = "regular",
    lastGroup = "regular"
  },
  SnowDrifter = {
    group = "guest",
    lastGroup = "guest"
  },
  Splicer9 = {
    group = "operator",
    lastGroup = "operator"
  },
  SumerSoft = {
    group = "guest",
    lastGroup = "guest"
  },
  Ta11er = {
    group = "guest",
    lastGroup = "guest"
  },
  TenshiIkari = {
    group = "moderator",
    lastGroup = "moderator"
  },
  Terminutter = {
    group = "guest",
    lastGroup = "guest"
  },
  TheThane = {
    group = "guest",
    lastGroup = "guest"
  },
  TheVictor27 = {
    group = "guest",
    lastGroup = "guest"
  },
  Thex2001 = {
    group = "guest",
    lastGroup = "guest"
  },
  Thuro = {
    group = "regular",
    lastGroup = "regular"
  },
  Tippythehuman = {
    group = "guest",
    lastGroup = "guest"
  },
  Trenzalorian = {
    group = "regular",
    lastGroup = "regular"
  },
  Uncertain_Knight = {
    group = "regular",
    lastGroup = "regular"
  },
  VikingCyborg = {
    group = "regular",
    lastGroup = "regular"
  },
  Zezztah = {
    group = "Jail",
    lastGroup = "Jail"
  },
  Zman98789 = {
    group = "guest",
    lastGroup = "guest"
  },
  Zoltanke = {
    group = "guest",
    lastGroup = "guest"
  },
  Zwulf = {
    group = "guest",
    lastGroup = "guest"
  },
  aegis549 = {
    group = "guest",
    lastGroup = "guest"
  },
  apocmonk = {
    group = "guest",
    lastGroup = "guest"
  },
  augentism = {
    group = "regular",
    lastGroup = "regular"
  },
  avaness = {
    group = "regular",
    lastGroup = "regular"
  },
  azimuth = {
    group = "regular",
    lastGroup = "regular"
  },
  baconman7 = {
    group = "guest",
    lastGroup = "guest"
  },
  basepsy = {
    group = "guest",
    lastGroup = "guest"
  },
  bogusfire774 = {
    group = "guest",
    lastGroup = "guest"
  },
  bondbill2k2 = {
    group = "guest",
    lastGroup = "guest"
  },
  brandon1311 = {
    group = "guest",
    lastGroup = "guest"
  },
  btroyer2011 = {
    group = "admin",
    lastGroup = "admin"
  },
  cocoilove = {
    group = "Jail",
    lastGroup = "Jail"
  },
  crispiy = {
    group = "regular",
    lastGroup = "regular"
  },
  crusty_ = {
    group = "guest",
    lastGroup = "guest"
  },
  darkdwight7 = {
    group = "regular",
    lastGroup = "regular"
  },
  dasocks = {
    group = "guest",
    lastGroup = "guest"
  },
  datadrian = {
    group = "regular",
    lastGroup = "regular"
  },
  dogigy = {
    group = "regular",
    lastGroup = "regular"
  },
  eckk = {
    group = "guest",
    lastGroup = "guest"
  },
  eltonnunes = {
    group = "guest",
    lastGroup = "guest"
  },
  fartingPuppy = {
    group = "guest",
    lastGroup = "guest"
  },
  funnysunnybunny = {
    group = "regular",
    lastGroup = "regular"
  },
  fuuunkow = {
    group = "Jail",
    lastGroup = "Jail"
  },
  generalsnipe = {
    group = "guest",
    lastGroup = "guest"
  },
  gofkrhffo = {
    group = "guest",
    lastGroup = "guest"
  },
  goobie = {
    group = "regular",
    lastGroup = "regular"
  },
  guoguomiao = {
    group = "guest",
    lastGroup = "guest"
  },
  halokillz = {
    group = "Jail",
    lastGroup = "Jail"
  },
  hearnsb = {
    group = "regular",
    lastgroup = "regular"
  },
  huds = {
    group = "guest",
    lastGroup = "guest"
  },
  immansuetus = {
    group = "regular",
    lastGroup = "regular"
  },
  inesoa = {
    group = "admin",
    lastGroup = "admin"
  },
  jacob3228 = {
    group = "Jail",
    lastGroup = "Jail"
  },
  jjs_112358 = {
    group = "regular",
    lastGroup = "regular"
  },
  jshearer = {
    group = "Jail",
    lastGroup = "Jail"
  },
  khopeshomen = {
    group = "Jail",
    lastGroup = "Jail"
  },
  kitosaurusrex = {
    group = "guest",
    lastGroup = "guest"
  },
  kova66 = {
    group = "guest",
    lastGroup = "guest"
  },
  kovus = {
    group = "operator",
    lastGroup = "operator"
  },
  ktrc199 = {
    group = "guest",
    lastGroup = "guest"
  },
  kunnis = {
    group = "regular",
    lastGroup = "regular"
  },
  l3igspeck = {
    group = "regular",
    lastGroup = "regular"
  },
  larsy7 = {
    group = "regular",
    lastGroup = "regular"
  },
  logansleg = {
    group = "regular",
    lastGroup = "regular"
  },
  ["lone-pine"] = {
    group = "guest",
    lastGroup = "guest"
  },
  mamac = {
    group = "guest",
    lastGroup = "guest"
  },
  marrygrim = {
    group = "regular",
    lastGroup = "regular"
  },
  matthew1206 = {
    group = "regular",
    lastGroup = "regular"
  },
  maxdeliso = {
    group = "guest",
    lastGroup = "guest"
  },
  mobieh22 = {
    group = "Jail",
    lastGroup = "Jail"
  },
  moonheart08 = {
    group = "regular",
    lastGroup = "regular"
  },
  mordof = {
    group = "guest",
    lastGroup = "guest"
  },
  mrMoops = {
    group = "guest",
    lastGroup = "guest"
  },
  mrhands = {
    group = "guest",
    lastGroup = "guest"
  },
  mt4577 = {
    group = "regular",
    lastGroup = "regular"
  },
  mzore = {
    group = "regular",
    lastGroup = "regular"
  },
  ndbassman = {
    group = "guest",
    lastGroup = "guest"
  },
  noobsuks = {
    group = "guest",
    lastGroup = "guest"
  },
  onthesub = {
    group = "guest",
    lastGroup = "guest"
  },
  pmalex = {
    group = "guest",
    lastGroup = "guest"
  },
  ponderer1 = {
    group = "guest",
    lastGroup = "guest"
  },
  quadmaster5 = {
    group = "guest",
    lastGroup = "guest"
  },
  quigro = {
    group = "regular",
    lastGroup = "regular"
  },
  redgerr = {
    group = "guest",
    lastGroup = "guest"
  },
  seeyorise = {
    group = "guest",
    lastGroup = "guest"
  },
  suzuxd = {
    group = "Jail",
    lastGroup = "Jail"
  },
  tecknurd = {
    group = "guest",
    lastGroup = "guest"
  },
  teewikit = {
    group = "guest",
    lastGroup = "guest"
  },
  themostinternet = {
    group = "admin",
    lastGroup = "admin"
  },
  tianlan33400 = {
    group = "guest",
    lastGroup = "guest"
  },
  tjgaming = {
    group = "guest",
    lastGroup = "guest"
  },
  tmoneyfizzle = {
    group = "Jail",
    lastGroup = "Jail"
  },
  typphon = {
    group = "guest",
    lastGroup = "guest"
  },
  tyshan2112 = {
    group = "guest",
    lastGroup = "guest"
  },
  valorfive = {
    group = "guest",
    lastGroup = "guest"
  },
  vk9i = {
    group = "Jail",
    lastGroup = "Jail"
  },
  vonlam999 = {
    group = "guest",
    lastGroup = "guest"
  },
  xTechnicalDude = {
    group = "guest",
    lastGroup = "guest"
  },
  xcal13 = {
    group = "guest",
    lastGroup = "guest"
  },
  xionSion = {
    group = "guest",
    lastGroup = "guest"
  },
  zactops = {
    group = "guest",
    lastGroup = "guest"
  },
  zumti = {
    group = "guest",
    lastGroup = "guest"
  }
}