--[[
	permission_definition.lua
	
	Distributed as Public Domain, with no license.
	This file can be generated by a script.
	
	See Factorio's Lua API for a list of actions:
	http://lua-api.factorio.com/latest/defines.html#defines.input_action
	NOTE: The list may not be accurate.  During 0.15.x, the list had 
	entries which had already been removed from the game, includine
	defines.input_action.nothing & .stop-walking.
--]]

return {
	default_group = 'guest', -- there MUST be a default group
	default_promote_group = 'regular',
	
	groups = {
		['jail2'] = {
			-- "SuperMax"
			-- basically, these are ban-worthy jailable users.
			i18n_name = {"permname.jail2"},
			i18n_sname = {"permname.jail2_short"},
			sort_rank = 1,
			permissions = {
			},
			inherit_perms_from = {},
		},
		['Jail'] = {
			-- Our Jail users should be able to communicate and defend their
			-- case, but not interact with the world.
			-- NOTE: the name of the "Jail" group is used in other places
			-- in the code!
			i18n_name = {"permname.jail"},
			i18n_sname = {"permname.jail_short"},
			sort_rank = 10,
			permissions = {
				'change_picking_state', 'drop_item', 'open_character_gui',
				'cancel_craft', 'write_to_console',
				'select_gun', 'stack_split', 'inventory_split', 'start_repair',
				'gui_elem_changed', 'gui_value_changed', 
			},
			inherit_perms_from = {'jail2'},
		},
		['guest'] = {
			-- New user, who has never been on the server.  Approach with
			-- caution, but let them be productive!
			i18n_name = {"permname.guest"},
			i18n_sname = {"permname.guest_short"},
			sort_rank = 20,
			permissions = {
				'build_item', 'start_walking', 'begin_mining', 'begin_mining_terrain',
				'rotate_entity', 'reverse_rotate_entity', 'toggle_driving',
				'change_riding_state', 'open_gui', 'open_item', 'open_equipment',
				'cursor_transfer', 'cursor_split', 'stack_transfer', 'inventory_transfer',
				'craft', 'wire_dragging', 'connect_rolling_stock', 'disconnect_rolling_stock',
				'change_shooting_state', 'toggle_entity_on_off_state', 'setup_assembling_machine',
				'shortcut_quick_bar_transfer', 'clean_cursor_stack', 'smart_pipette',
				'select_item', 'reset_assembling_machine', 'set_filter',
				'set_autosort_inventory', 'open_technology_gui', 'set_circuit_condition',
				'set_signal', 'start_research',
				'set_logistic_filter_item', 'set_logistic_filter_signal',
				'switch_constant_combinator_state', 'switch_power_switch_state',
				'switch_connect_to_logistic_network', 'set_circuit_mode_of_operation',
				'set_behavior_mode', 'fast_entity_transfer', 'fast_entity_split',
				'gui_click', 'market_offer', 'edit_train_schedule',
				'set_train_stopped', 'change_train_stop_station',
				'change_active_item_group_for_crafting', 'set_use_item_groups',
				'gui_text_changed', 'gui_checked_state_changed', 'gui_selection_state_changed',
				'place_equipment', 'take_equipment', 'use_ability', 'use_item',
				'change_active_quick_bar', 'open_blueprint_library_gui',
				'open_production_gui', 'open_kills_gui', 'set_inventory_bar',
				'change_active_item_group_for_filters', 'select_blueprint_entities',
				'alt_select_blueprint_entities', 'setup_blueprint',
				'set_blueprint_icon', 'cancel_new_blueprint', 'setup_single_blueprint_record',
				'set_single_blueprint_record_icon', 'open_blueprint_record', 'craft_blueprint_record',
				'change_single_blueprint_record_label', 'grab_blueprint_record', 'drop_blueprint_record',
				'delete_blueprint_record', 'create_blueprint_like', 'change_blueprint_book_record_label',
				'copy_entity_settings', 'paste_entity_settings', 'remove_cables',
				'clear_blueprint', 'destroy_opened_item', 'export_blueprint',
				'import_blueprint', 'toggle_show_entity_info',
				'change_arithmetic_combinator_parameters',
				'change_decider_combinator_parameters',
				'change_programmable_speaker_parameters',
				'change_programmable_speaker_alert_parameters',
				'change_programmable_speaker_circuit_parameters',
				'set_inserter_max_stack_size', 'build_terrain',
				'change_train_wait_condition', 'change_train_wait_condition_data',
				'custom_input', 'change_item_label', 'build_rail', 'open_train_gui',
				'switch_to_rename_stop_gui', 'open_bonus_gui', 'open_trains_gui',
				'open_achievements_gui', 'open_tutorials_gui', 'cancel_research',
				'open_train_station_gui', 'select_area', 'alt_select_area',
				'set_entity_color', 'clear_selected_blueprint', 'clear_selected_deconstruction_item',
				'cycle_blueprint_book_forwards', 'cycle_blueprint_book_backwards',
				'set_logistic_trash_filter_item', 'toggle_enable_vehicle_logistics_while_moving',
				'select_entity_slot', 'select_tile_slot', 'toggle_deconstruction_item_entity_filter_mode',
				'cancel_deconstruct',
				'toggle_deconstruction_item_tile_filter_mode',
				'set_deconstruction_item_trees_and_rocks_only',
				'set_deconstruction_item_tile_selection_mode',
				'open_logistic_gui', 'mod_settings_changed', 'set_entity_energy_property',
				'drop_to_blueprint_book', 'edit_custom_tag', 'delete_custom_tag',
				'toggle_connect_front_center_tank', 'toggle_connect_center_back_tank',
				'import_blueprint_string', 'gui_elem_selected',
				'open_mod_item', 'drag_train_schedule', 'drag_train_wait_condition',
				'set_car_weapons_control', 'set_request_from_buffers',
				'set_infinity_container_filter_item', 'set_infinity_container_remove_unfiltered_items',
				'set_splitter_priority',
			},
			autopromote = {
				time = 3600, -- seconds. (assumes 60 ticks/sec)
				to = 'regular',
			},
			inherit_perms_from = {'Jail'},
		},
		['regular'] = {
			-- Active player.
			i18n_name = {"permname.regular"},
			i18n_sname = {"permname.regular_short"},
			sort_rank = 30,
			permissions = {
				'launch_rocket', 'set_auto_launch_rocket', 'deconstruct',
				'use_artillery_remote', 
			},
			inherit_perms_from = {'guest'},
		},
		['moderator'] = {
			-- People to whom we would entrust managing user interactions
			-- Eg: jailing the bad people, 
			i18n_name = {"permname.moderator"},
			i18n_sname = {"permname.moderator_short"},
			sort_rank = 40,
			permissions = {
				'admin.tool', 'admin.tool.set_jail', 'admin.tool.set_rank',
				'admin.tool.bring', 'admin.tool.bringall',
			},

			inherit_perms_from = {'regular'},
		},
		['admin'] = {
			i18n_name = {'permname.admin'},
			i18n_sname = {'permname.admin_short'},
			sort_rank = 50,
			permissions = {
				'admin.tool.kill',
				'admin.tool.dump_inventory',
				'admin.tool.open_inventory',
				'admin.tool.revive_ents',
				'set_research_finished_stops_game',
			},
			inherit_perms_from = {'moderator'},
		},
		['operator'] = {
			i18n_name = {"permname.operator"},
			i18n_sname = {"permname.operator_short"},
			should_have_all_perms = true, -- should have all Factorio permissions
			sort_rank = 9999,
			permissions = {
				'advadmin.tool',
				'add_permission_group', 'delete_permission_group', 'edit_permission_group',
			},
			inherit_perms_from = {'admin'},
		},
	},
}